### ISSUE TITLE
"undefined" message stops all the commits from Doc to Github

### ISSUE THREAD

**Issue by cirospat** [iapyeh/GGeditor#1]
"**undefined**" message stops all the commits from Google Doc to Github, even in the Docs that before were perfect working (on commit procedure).

When creating new Docs and trying to Commit to Github this message appears:
![image](https://user-images.githubusercontent.com/3757525/38125589-d2b06546-33ea-11e8-9ef4-9b4c24ce3e63.png)

I'm using your perfect tutorial (on RTD) and trying to translate it in italian language:
http://cirospat.readthedocs.io
so to be adopt by many public employees (I work for Municipality of Palermo, Italy).

Please check this issue, because I cannot proceed in my work
thanks very much for the attention,
Ciro

**Comment by cirospat** [comment]
I write you back (email).
I shared the Google Drive folder with you in editing so that you can try the Commit with GGeditor.

I tryed to perform Commit once again after your email answer but the problem persist.
Try to enter in the docs and commit to Github by yourself, so that you can experience the problem.

I have the doc named "User Guide" that is not committed to Github till now.

Thanks for your precious help.

**Comment by cirospat** [comment]
Iapyeh solved the problem with a release of the GGeditor plugin (dated 1 april 2018).
Feature: added a reset button on Settings/About window. It is to sanitize stored binding data if necessary.

**Comment by iapyeh** [comment]
Appreciation for great help and patience of Ciro. It was a outcome of our coordination. This issue will be closed temporary, though at this moment, I have no idea about the root cause which leads to the broken individual settings. Any information updating on the same issue is welcomed.
