### ISSUE TITLE
Would you mind adding a LICENSE file?

### ISSUE THREAD

**Issue by mithro** [iapyeh/GGeditor#5]
Currently this repository doesn't seem to have any licensing information in it. Would you be able to add a LICENSE file?

GitHub has some instructions on how to do this @ https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository
They also have a site called https://choosealicense.com/ which helps you figure out which license you might want to use.

There is some information about why this is important at;
 - https://choosealicense.com/no-permission/
 - https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by iapyeh** [comment]
Hi Thank you. It is done. It is really simple,  just follow all green buttons.

**Comment by mithro** [comment]
Thank you, it is greatly appreciated!
